name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
  
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/blockhouse_worktrial
            git pull origin main
            docker build -t trade_order_api .

            if [ $(docker ps -q -f name=trade_order_api) ]; then
                docker stop trade_order_api
                docker rm trade_order_api
            fi

            PORT_PID=$(sudo lsof -t -i:8000)
            if [ ! -z "$PORT_PID" ]; then
                sudo kill -9 $PORT_PID
            fi

            docker run -d --name trade_order_api -p 8000:8000 trade_order_api
          EOF
